[package]
name = "flash_user"
version = "0.1.0"
edition = "2021"

[dependencies]
flash_core = { path = "../flash_core" }
axum = { version = "0.7", features = ["ws"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.7", features = ["runtime-tokio", "tls-native-tls", "postgres", "uuid", "chrono", "migrate"] }
bcrypt = "0.15"
rand = "0.8"
thiserror = "1"
jsonwebtoken = "9"
